version: 0.2

phases:
 build:
   commands:
     - echo Packaging app on `date`
     - mvn clean package
     - echo Executing packaging on cloudformation on s3 bucket s3://codepipeline-us-east-1-958283805552/user-service.jar
     - aws cloudformation package --template-file sam.yaml --output-template-file output-sam.yaml --s3-bucket s3://codepipeline-us-east-1-958283805552/user-service.jar
     - echo Executing deploying on cloudformation with stack called UserMicroserviceSpringBoot
     - aws cloudformation deploy --template-file output-sam.yaml --stack-name UserMicroserviceSpringBoot --capabilities CAPABILITY_NAMED_IAM
 post_build:
   commands:
     - echo App packaged on `date`.
artifacts:
 type: zip
 files:
   - "target/user-service.jar"
   - "Procfile"
   - "sam.yaml"
 discard-paths: yes