version: 0.2

phases:
 build:
   commands:
     - echo Packaging app on `date`
     - mvn clean package
 post_build:
   commands:
     - echo App packaged on `date`.
artifacts:
 type: zip
 files:
   - "target/spring-boot-aws-lambda.jar"
   - "Procfile"
   - "serverless.yml"
 discard-paths: yes