AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: First Java Lamdba Project
Resources:
  UserService:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UserService
      Handler: rio.brunorodrigues.function.handle.LambdaHandler::handleRequest
      Runtime: java8
      CodeUri: ./target/user-service.jar
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Tags:
        -
          Key: "user-service"
          Value: "user-service"
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /users
            Method: GET
        PostResource:
          Type: Api
          Properties:
            Path: /users
            Method: POST
        RetrieveResource:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: GET
Outputs:
  SpringBootUserServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/users'
    Export:
      Name: SpringBootUserServiceApi