AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: First Java Lamdba Project
Resources:
  UserServiceApi:
    DependsOn:
      - UserServiceFunction
    Properties:
      StageName: Dev
      DefinitionBody:
        swagger: 2.0
        info:
          title:
            Ref: AWS::StackName
        paths:
          /users:
            get:
              responses: {}
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserServiceFunction.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
  UserService:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UserServiceFunction
      Handler: rio.brunorodrigues.function.handle.LambdaHandler::handleRequest
      Runtime: java8
      CodeUri: ./target/user-service.jar
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /users
            Method: GET
        PostResource:
          Type: Api
          Properties:
            Path: /users
            Method: POST
        RetrieveResource:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: GET
Outputs:
  SpringBootUserServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/users'
    Export:
      Name: SpringBootUserServiceApi