AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: First Java Lamdba Project
Resources:
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: rio.brunorodrigues.function.handle.LambdaHandler::handleRequest
      Runtime: java8
      CodeUri: s3://codepipeline-us-east-1-958283805552/user-service.jar
      MemorySize: 1512
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaExecute # Managed Policy
          - Version: '2012-10-17' # Policy Document
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectACL
               Resource: 'arn:aws:s3:::codepipeline-us-east-1-958283805552/*'
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SpringBootPetStoreApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/users'
    Export:
      Name: SpringBootPetStoreApi