service: First_Application_In_AWS_Lambda

provider:
  name: aws
  runtime: java8
  memorySize: 1536
  timeout: 60

package:
  artifact: build/distributions/springboot-lambda.zip

functions:
  users:
    handler: rio.brunorodrigues.function.LambdaHandler
    events:
      - http:
          path: users
          method: get
          cors: true
      #- http:
      #    path: users/{lastName}
      #    method: get
      #    cors: true
      #- http:
      #    path: users/create
      #    method: post
      #    cors: true